spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.52.54.67:3306/wesports?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: Wesport2020@

  redis:
    host: 106.52.54.67
    port: 6379
    password: wesports
# service version
wesports:
  service:
    version: 1.0.dev

# redis config


# Dubbo Config properties
dubbo:
  application:
    id: wesportrs-company-dev
    name: wesportrs-company-dev
    qos-enable: false
  registry:
    protocol: zookeeper
    address: 106.52.54.67:2181
  protocol:
    name: dubbo
    port: 20883
  provider:
    timeout: 300000


---
spring:
  profiles: uat

# service version
wesports:
  service:
    version: 1.0

# redis config
redis:
  host: 106.52.54.67
  port: 6379
  password: wesports

# Dubbo Config properties
dubbo:
  application:
    id: wesports-company
    name: wesports-company
    registry:
      protocol: zookeeper
      address: 106.52.54.67:2181

