spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/wesports?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: helloworld
      filters: log4j,wall,mergeStat
      driver-class-name: com.mysql.jdbc.Driver

# service version
wesports:
  service:
    version: 1.0.dev

# redis config
redis:
  host: 106.52.54.67
  port: 6379
  password: wesports

# Dubbo Config properties
dubbo:
  application:
    id: wesports-service-dev
    name: wesports-service-dev
    qos-enable: true
    qos-port: 22223
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882
  provider:
    timeout: 300000
# web port
server:
  port: 9990
# mysql



---
spring:
  profiles: uat

# service version
wesports:
  service:
    version: 1.0

# redis config
redis:
  host: 106.52.54.67
  port: 6379
  password: wesports

# Dubbo Config properties
dubbo:
  application:
    id: wesports-service
    name: wesports-service
    qos-enable: true
    qos-port: 22223
  registry:
    protocol: zookeeper
    address: 106.52.54.67:2181
  protocol:
    name: dubbo
    port: 20882
  provider:
    timeout: 5000

#web port
server:
  port: 9990

